// src/nanoswarm/commands.rs
// 150+ nanoswarm command variants, for safe programmable swarms

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum NanoSwarmCommand {
    MoveTo { location: [f64;3] },
    HoldPosition,
    Retreat,
    Advance,
    PatrolRoute { points: Vec<[f64;3]> },
    ScanArea,
    Recon,
    MapTerrain,
    ReportThreat { threat_id: u64 },
    MarkTarget { target_id: u64 },
    TagEntity { entity_id: u64 },
    FollowEntity { entity_id: u64 },
    EscortEntity { entity_id: u64 },
    SurroundTarget { target_id: u64, radius: f32 },
    DeliverPayload { payload_type: String, target_id: u64 },
    AbsorbRadiation,
    AbsorbContaminant { contaminant: String },
    DisperseAgent { agent: String },
    EmitSignal { signal_type: String },
    SuppressSignal { signal_type: String },
    NeutralizeSignal { signal_type: String },
    CleanSurface,
    CleanAir,
    CleanWater,
    DecontaminateZone,
    PurifyWater,
    BoilWater,
    SterilizeEquipment,
    SanitizeArea,
    Disinfect,
    RemoveOdor,
    ApplySealant,
    PatchSurface,
    RepairDevice { device_id: u64 },
    RestoreFirmware { device_id: u64 },
    RecalibrateSensor { sensor_id: u64 },
    TuneFrequency { frequency: f64 },
    DeployMeshNetwork,
    ExtendWifiRange,
    RelayData,
    CollectSample { sample_type: String },
    AnalyzeSample { sample_id: u64 },
    AnalyzeAirQuality,
    AnalyzeSoil,
    AnalyzeWater,
    MeasureTemperature,
    MeasureRadiation,
    TestForPathogens,
    DeploySensorNode { location: [f64;3] },
    GenerateMap,
    UpdateMap,
    TransmitMap,
    RecordAudio,
    RecordVideo,
    ProvideLiveFeed,
    StreamData,
    TakePhotograph,
    MarkWaypoint,
    LeaveBreadcrumb,
    SetBeacon,
    RemoveBeacon,
    DetectIntrusion,
    TrackMovement,
    MonitorArea,
    DetectAnomaly,
    RespondAlarm,
    JamDevice { device_id: u64 },
    UnjamDevice { device_id: u64 },
    InhibitMotion { target_id: u64 },
    ImmobilizeEntity { entity_id: u64 },
    DisarmTrap,
    DisarmDevice,
    DisableWeapon { weapon_id: u64 },
    CaptureEntity { entity_id: u64 },
    RestrainTarget { target_id: u64 },
    GuardZone,
    CreateBarrier,
    FortifyStructure,
    BuildTrap,
    LayMine,
    ClearMine,
    ExplodeOnCommand,
    DefuseExplosive,
    NeutralizeToxin,
    NeutralizePathogen,
    DeliverAntidote,
    ApplyMedicine,
    ApplyBandage,
    StimulateHealing,
    ResealWound,
    ReportInjury { entity_id: u64 },
    ConductSurgery,
    InjectSubstance { substance: String, entity_id: u64 },
    AdministerVaccine { entity_id: u64 },
    AssessVitals { entity_id: u64 },
    DeliverNutrient,
    HarvestResource { resource: String },
    ExtractMineral,
    CollectDebris,
    RecycleMaterial,
    FabricateObject { blueprint_id: u64 },
    PrintComponent { component: String },
    MoldStructure,
    AssembleModule,
    DisassembleObject { object_id: u64 },
    DismantleDevice { device_id: u64 },
    Salvage,
    UpgradeFirmware { device_id: u64 },
    PatchSoftware { device_id: u64 },
    BackupData { device_id: u64 },
    RestoreData { backup_id: u64 },
    EncryptChannel,
    DecryptChannel,
    AuthenticateUser { user_id: u64 },
    GrantAccess { user_id: u64, access_level: u8 },
    RevokeAccess { user_id: u64 },
    LockdownZone,
    UnlockZone,
    ActivateAlarm,
    DeactivateAlarm,
    IdentifyEntity { entity_id: u64 },
    MonitorHealth { entity_id: u64 },
    LogActivity,
    SummarizeIncident,
    NotifySupervisor { message: String },
    SyncWithCloud,
    EnterStealthMode,
    ExitStealthMode,
    Camouflage,
    SelfDestruct,
    SleepMode,
    Wake,
    Reboot,
    Recharge,
    PowerDown,
    PowerUp,
    DistributePower,
    HarvestSolar,
    HarvestThermal,
    StoreEnergy,
    TransferEnergy { target_id: u64 },
    BalanceLoad,
    EscalateToHuman,
    RequestAssistance,
    AcknowledgeOrder,
    CancelOrder,
    RepeatOrder,
    PauseOperation,
    ResumeOperation,
    UpgradeHardware,
    TestSystem,
    RunDiagnostics,
    ReportMalfunction,
    EmergencyShutdown,
    IsolateFault,
    QuarantineSubsystem,
    InitiateRecovery,
    ExportLogs,
    ImportConfig,
    SyncSettings,
    UpdateFirmware,
    OptimizePath,
    AdaptBehavior,
    LearnFromExample,
    TrainModel,
    DeployAI,
    RollbackUpdate,
    SecureZone,
    AuthorizeOverride,
    RejectOrder,
    AwaitCommand,
    ExecutePlan { plan_id: u64 },
    AbortMission,
    ConfirmSuccess,
    ReportCompletion,
    ArchiveData,
    SignalVictory,
    SignalDefeat,
    Celebrate,
    CalibrateTime,
    CalibratePosition,
}
